# Generated by Django 6.0.3 on 2026-04-05 21:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("forum", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="posts",
            name="code",
            field=models.FileField(upload_to="forum/code/"),
        ),
    ]
